name: samayakuri
version: 0.1.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.1.4
  path: 1.8.0
  shared_preferences: ^2.0.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  fonts:
    - family: MeriendaOne
      fonts:
       - asset: assets/fonts/MeriendaOne-Regular.ttf 

